### ISSUE TITLE
Fail to run in production mode with ssl (nginx proxy)

### ISSUE THREAD

**Issue by c3b-watzefak** [aholbreich/docker-ghost#1]
Hi there!

I use nginx mainline to get a reverse proxy for your "dockered" ghost. Without any ssl-config the blog main page is reachable. The tutorial used is: [http://pnommensen.com/2014/09/07/high-performance-ghost-configuration-with-nginx/](url)

After inserting ssl-configs the blog is still reachable but when clicking on any link or pointing the browser to the admin panel, there is always in every browser the error: too many redirects...

Can you help me?

**Comment by aholbreich** [comment]
hi
i can try, but need more details. 
Your link is brocken so i cannot see any details. Which SSL configs you mean? Provide whole configuration please.

**Comment by c3b-watzefak** [comment]
These are the configs:

https://gist.github.com/c3b-watzefak/aad75fb26b2570f26cc6319daaabb7a6

This is the command I used to get ghost running:

`docker run -d --name c3b-ghost-prod -h c3b.info --env-file /opt/docker.conf/c3b.info/ghost.conf/ghost -p 127.0.0.1:2368:2368 -v /opt/docker.conf/c3b.info/ghost.store:/var/lib/ghost --restart=always gold/ghost npm start --production`

**Comment by c3b-watzefak** [comment]
By the way: I cross checked just now to run the official ghost docker. It is working on dev-mode with the configuration above...

**Comment by aholbreich** [comment]
I' will try to build similar setup.

1)But could you provide also env file (/opt/docker.conf/c3b.info/ghost.conf/ghost). that is missing part.

2)Can you check the dev mode start with gold/ghost? 
Official image developer mode do not enable SSL on ghost admin page, so i expect similar behavior with gold/ghost.

In production SSL is enabled at least for admin pages. So the upstream configuration seem not to match... 

3) Are you able to access blog directly on exposed ports bypassing nginx? So please make sure container is running and working as expected without nginx first. So we can limit the problem to ghost pasrt or to nginx part.

**Comment by c3b-watzefak** [comment]
1) /opt/docker.conf/c3b.info/ghost.conf/ghost

```
# Ghost environment example
# Place in /etc/default/ghost

GHOST_URL=http://c3b.info
MAIL_FROM='"Webmaster" <webmaster@c3b.info>'
MAIL_HOST=c3b.info
PROD_FORCE_ADMIN_SSL=false
```

2)Yes, like u said, front page loaded, none of the links and admin page is working

3) I am able to reach the blog without nginx on its port. but not on ssl

**Comment by aholbreich** [comment]
3) Yes this is Ok because of PROD_FORCE_ADMIN_SSL=false. But do you have any problems whith ghost (without SSL) if you use it directly without nginx.? 

It seems like there is a bug in nginx config that do not consider some redirection turns to cycle... Have you looked in your nginx (error) log?

**Comment by c3b-watzefak** [comment]
I think I got it. In the nginx configs for the proxy was a autoforward to https from http. I have to proxy http aswell as https then it runs good. Testing for the moment...

**Comment by c3b-watzefak** [comment]
Okay, if you want to run your docker image behind a nginx proxy, you will have to proxy both protocols, http like https. I don't know why but that workaroud keeps on running on c3b.info

I close that issue now

**Comment by aholbreich** [comment]
I plan to test it in the future and add some documentation on it.
Currently i run different setup.
Thank you for the feedback anyway.
